feat: реализация ShareIt согласно ТЗ ФП спринта №14
SZFO/java-shareit pull request #1
Opened 2022-10-17 19:10 UTC by SZFO

2022-10-18 18:12 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/Create.java
> +package ru.practicum.shareit;
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку 
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём. 
Потом по степени "тяжеловестности" остальные зависимости

ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/Create.java
> +
И про файл настроек `application.properties`, так как он не менялся, тоже тут напишу...

Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели ))

Соответственно - попрошу тебя этому следовать.

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ExceptionHandler(ValidateException.class)
Лучше назвать класс исключения в соответствии с HttpStatus кодом.
т.е. `ConflictException`

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ExceptionHandler(RuntimeException.class)
В общем случае сервер должен кидать 500 код `INTERNAL_SERVER_ERROR`

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String USER_ID = "X-Sharer-User-Id";
Обоснуй, зачем добавлен модификатор `static`?

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ResponseEntity.ok().build();
`ResponseEntity` это уже как бы следующий уровень. 
Если применил его тут, почему же не применил его везде?

При удалении, по REST, корректным статус кодом будет 204, а не 200!

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        log.info("Вызван метод delete() в ItemController");
Добавляй в лог полезной информации... 
По какому id происходит удаление!?

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
Моделям не нужны аннотации валидации... их не валидируют при входе. Валидируют dto-шки.

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Boolean available;
Почему отсутствует `requestId`?

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String name;
А `name` может быть пустым? 
Не забыл ли ты добавить валидации тут?

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank(groups = {Create.class})
Хорошо что используешь группировки... но почему только одну при `create`.
Если она одна то это бессмысленно... Что там при обновлении, не отличается ли, например поле `email`?

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +public interface UserService {
Нет желания вывести универсальный интерфейс?

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    private void validateEmail(String email) {
Пучёк претензий к этому методу...

- Название. Валидация предусматривает возвращение результата. А если ты собрался просто бросать исключение по условию то лучше назвать метод честно: `throwIfExist`
- Надо не в `if` запихивать вот эту длинную цепочку, а наоборот... надо написать код так чтобы выйти на Optional и воспользовавшись им сделать что нужно (попытался не дать прямого ответа, а просто подтолкнуть тебя, не знаю получится нет, в общем попробуй переделать)
- Есть метод `equalsIgnoreCase`

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        return UserMapper.userToDto(userRepository.create(user));
Можно заимпортить статик метод `return userToDto(userRepository.create(user));`

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        Item oldItem = itemRepository.getById(itemId).get();
Нельзя `.get()` без проверки...

2022-10-18 18:12 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (oldItem.getOwner() == owner) {
Лучше инвертировать условие

```
        if (oldItem.getOwner() != owner) {
            throw new NotFoundException("Редактировать информацию о вещи может только ее владелец.");
        }
        
        и `else`  не понадобиться...
```

2022-10-20 21:20 UTC, SZFO commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String USER_ID = "X-Sharer-User-Id";
Решил, что данная переменная - глобальная константа

2022-10-20 21:25 UTC, SZFO commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ResponseEntity.ok().build();
Вот только если сделать код 204 [No Content] в UserController, то провален тест в Postman.
В ItemController код 204 в тестах проходит, потому что теста такого нет))
![Снимок экрана от 2022-10-21 00-21-45](https://user-images.githubusercontent.com/99078873/197061664-44dff0a8-112f-4f6f-8d25-7879e66d7b63.png)

2022-10-20 21:25 UTC, SZFO commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        log.info("Вызван метод delete() в ItemController");
Поправил

2022-10-20 21:25 UTC, SZFO commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ExceptionHandler(RuntimeException.class)
Исправил

2022-10-20 21:25 UTC, SZFO commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ExceptionHandler(ValidateException.class)
Исправил

2022-10-20 21:26 UTC, SZFO commented on src/main/java/ru/practicum/shareit/Create.java
> +
Исправил

2022-10-20 21:26 UTC, SZFO commented on src/main/java/ru/practicum/shareit/Create.java
> +package ru.practicum.shareit;
Постарался расположить корректно

2022-10-20 21:26 UTC, SZFO commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
Исправил

2022-10-20 21:27 UTC, SZFO commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Boolean available;
Добавил. Упустил, так как в этом спринте он не используется.

2022-10-20 21:27 UTC, SZFO commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String name;
Забыл)) Исправлено

2022-10-21 04:29 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ResponseEntity.ok().build();
Принято!
Мы регулярно отправляем такого рода инфу и тесты прокачивают, спасибо!

2022-10-22 08:01 UTC, SZFO commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank(groups = {Create.class})
Да, проверка нужна, согласен

2022-10-22 08:02 UTC, SZFO commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        Item oldItem = itemRepository.getById(itemId).get();
Исправил

2022-10-22 08:02 UTC, SZFO commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (oldItem.getOwner() == owner) {
Исправил

2022-10-22 08:02 UTC, SZFO commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        return UserMapper.userToDto(userRepository.create(user));
Согласен, со статическим импортом смотрится лучше.

2022-10-22 08:06 UTC, SZFO commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +public interface UserService {
Для хранилища без проблем. Интерфейс Storage. Методы ведь для Item и User одинаковые. 
А вот для сервиса не осилил. Для Item и User только методы create, update и delete совпадают.

2022-10-22 08:09 UTC, SZFO commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    private void validateEmail(String email) {
Через Optional возился, но так и не пришёл к чему-то стоящему. Получалась более нагромождённая конструкция что ли. 
В итоге причесал метод и переименовал его в throwCrossEmail().

2022-10-22 12:35 UTC, FanaticFiz approved these changes

2022-10-22 12:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.info("Ошибка: {}", e.getMessage());
Желательно логгирование со стектрейсом

```
log.info("Ошибка: {}", e.getMessage(), e);
```

2022-10-22 12:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return ResponseEntity.ok().body(itemService.getAllByOwner(ownerId)).getBody();
Не прячь вот так основное действие, лучше уделить ему одну строку кода.

```
        List<ItemDto> allByOwner = itemService.getAllByOwner(ownerId);
        
        return ResponseEntity.ok().body(allByOwner).getBody();
```

2022-10-22 12:35 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        return itemToDto(itemRepository.getById(id)
Снова лучше разделять... чтобы было чётко видно два действия
- достали или бросили ексепшн
- вернули перемапив

```
    @Override
    public ItemDto getById(int id) {
        Item item = itemRepository.getById(id)
                                  .orElseThrow(() -> new NotFoundException("Не найдена вещь с id: " + id)));

        return itemToDto(item);
    }
```

2022-10-23 13:21 UTC, merged